export default function handler(req, res) {
  res.status(200).json([
    {
      id: 1,
      title: "Lorem ipsum dolor sit amet",
      images: [
        "jannik-skorna-mY2ZHBU6GRk-unsplash.jpg",
        "jannik-skorna-mY2ZHBU6GRk-unsplash.jpg",
        "jannik-skorna-mY2ZHBU6GRk-unsplash.jpg",
      ],
      word: {
        access: "Consectetur adipiscing elit",
        pool: "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
        cancellation: "Ut enim ad minim veniam",
      },
      description_words: {
        peaceful: 0,
        unique: 0,
        family_friendly: 0,
        stylish: 0,
        central: 0,
        spacious: 0,
      },
      description:
        "Your family will be close to everything when you stay at this centrally-located place.",
      price_per_night: "445",
      prohibitions: {
        security_cameras: 0,
        weapons: 0,
        dangerous_animals: 0,
      },
      type: {
        house: 1,
        apartment: 0,
        barn: 0,
        bed_and_breakfast: 0,
        boat: 0,
        cabin: 0,
        camper: 0,
        castle: 0,
        cave: 0,
        container: 0,
        cycladic_home: 0,
        dammuso: 0,
        dome: 0,
        earth_dome: 0,
        farm: 0,
        guesthouse: 0,
        hotel: 0,
        houseboat: 0,
        kezhan: 0,
        minsu: 0,
        riad: 0,
        ryokan: 0,
        shepherds_hut: 0,
        tend: 0,
        tiny_home: 0,
        tower: 0,
        treehouse: 0,
        trullo: 0,
        windmill: 0,
        yurt: 0,
      },
      type2: {
        whole_place: 1,
        private_room: 0,
        shared_room: 0,
      },
      approximate_location: "Sweden, Stockolm",
      exaxt_location: "Lorem ipsum dolor sit amet",
      guests: 7,
      bedrooms: [
        {
          beds: 2,
          images: [
            "jannik-skorna-mY2ZHBU6GRk-unsplash.jpg",
            "jannik-skorna-mY2ZHBU6GRk-unsplash.jpg",
            "jannik-skorna-mY2ZHBU6GRk-unsplash.jpg",
          ],
        },
        {
          beds: 2,
          images: [
            "jannik-skorna-mY2ZHBU6GRk-unsplash.jpg",
            "jannik-skorna-mY2ZHBU6GRk-unsplash.jpg",
            "jannik-skorna-mY2ZHBU6GRk-unsplash.jpg",
          ],
        },
      ],
      bathrooms: 2,
      amenities: {
        essential: {
          wifi: 1,
          tv: 1,
          kitchen: 1,
          washer: 1,
          free_parking_on_premises: 1,
          paid_parking_on_premises: 1,
          air_conditioning: 1,
          dedicated_workspace: 1,
        },
        standout: {
          pool: 1,
          hot_tub: 0,
          patio: 0,
          bbq_grill: 0,
          outdoor_dining_area: 0,
          fire_pit: 0,
          pool_table: 0,
          indoor_fireplace: 0,
          piano: 0,
          exercise_equipment: 0,
          lake_access: 0,
          beach_access: 0,
          hot_tub: 0,
          ski_in_ski_out: 0,
          outdoor_shower: 0,
        },
        scenic: {
          courtyard_view: 1,
          garden_view: 1,
          pool_view: 1,
        },
        bathroom: {
          hair_dryer: 1,
          cleaning_products: 1,
          conditioner: 1,
          body_soap: 1,
          hot_water: 1,
        },
        safety_items: {
          smoke_alarm: 0,
          first_aid_kit: 0,
          sire_extinguisher: 0,
          carbon_monoxide_alarm: 0,
        },
        bedroom_and_laundry: {
          essentials: {
            towels: 1,
            bed_sheets: 1,
            soap: 1,
            tiolet_paper: 1,
          },
          hangers: 1,
          bed_linens: 1,
          extra_pillows_and_blankets: 1,
          iron: 1,
          drying_rak_for_clothing: 1,
          mosquito_net: 1,
          clothing_storage: 1,
        },
      },
      rules: {
        pets_allowed: 0,
        events_allowed: 0,
        smoking_allowed: 0,
        commercial_photography: 0,
        events_allowed: 0,
        quiet_hours: {
          start_time: null,
          end_time: null
        },
        guests_number: 8,
      }
    },
  ]);
}
